# Generated by Django 4.2 on 2023-05-04 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('product_description', models.TextField()),
                ('stock_status', models.CharField(choices=[('IN_STOCK', 'In stock'), ('IN_STOCK_WITH_SUPPLIER', 'In stock with supplier'), ('OUT_OF_STOCK', 'Out of stock')], max_length=25)),
                ('price', models.PositiveIntegerField()),
                ('sale_price', models.PositiveIntegerField()),
                ('image_file', models.CharField(max_length=20)),
                ('component_category', models.CharField(choices=[('FANS_AND_CPU_COOLERS', 'Fans & CPU Coolers'), ('CASES_CHASSIS', 'Cases / Chassis'), ('LAPTOP_NOTEBOOK', 'Laptops / Notebooks')], default=('FANS_AND_CPU_COOLERS', 'Fans & CPU Coolers'), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productmodel')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productmodel')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
