# Generated by Django 4.2 on 2023-05-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_productmodel_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image_file',
            field=models.CharField(max_length=200),
        ),
    ]
