# Generated by Django 4.2 on 2023-05-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_productmodel_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sale_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='WishlistModel',
        ),
    ]
